// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: bjezmrrwefesihnftjje

class SupabaseConfig {
  static const String supabaseUrl = 'https://bjezmrrwefesihnftjje.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZXptcnJ3ZWZlc2lobmZ0amplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTAxNDQsImV4cCI6MjA4MDI2NjE0NH0.ZEymGYEu6sy2ZPSvBxH_StqR2hKxJ-nihzat0R2zUNc';
}
